{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ tpl .Values.cookieSecret.name $ }}
spec:
  refreshInterval: {{ .Values.cookieSecret.refreshInterval }}
  target:
    name: {{ tpl .Values.cookieSecret.name $ }}
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ tpl .Values.cookieSecret.name $ }}
{{- end }}