{{- if .Values.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ tpl .Values.cookieSecret.name $ }}
spec:
  length: {{ .Values.cookieSecret.length }}
  digits: {{ .Values.cookieSecret.digits }}
  symbols: {{ .Values.cookieSecret.symbols }}
  symbolCharacters: {{ quote .Values.cookieSecret.symbolCharacters }}
  noUpper: {{ .Values.cookieSecret.noUpper }}
  allowRepeat: {{ .Values.cookieSecret.allowRepeat }}
{{- end }}